languageCode = "en-us"
title = "Radoslava Kordeková / VIP Zvěřina"
baseURL = "/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

 [params]
  # set below parameter to define a favicon
  favicon = "images/favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

[params.posts]
  folderName = "post"
 
[languages]
[languages.en]
  languageName = "English"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"